// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function getBase(p) {
  return p.base;
}

function getIndex(p) {
  return p.index;
}

function sameSquare(p1, p2) {
  return p1.base === p2.base;
}

var Part = {
  getBase: getBase,
  getIndex: getIndex,
  sameSquare: sameSquare
};

exports.Part = Part;
/* No side effect */
