// Generated by ReScript, PLEASE EDIT WITH CARE


function baseIsValid(b) {
  return 1 <= b;
}

function totalCountOfCells(b) {
  return Math.imul(b, b);
}

function totalRows(b) {
  return b;
}

function totalColumns(b) {
  return b;
}

function totalSlants(b) {
  return (b << 1) - 1 | 0;
}

export {
  baseIsValid ,
  totalCountOfCells ,
  totalRows ,
  totalColumns ,
  totalSlants ,
  
}
/* No side effect */
