// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function baseIsValid(b) {
  return 1 <= b;
}

function totalCountOfCells(b) {
  return Math.imul(b, b);
}

function totalRows(b) {
  return b;
}

function totalColumns(b) {
  return b;
}

function totalSlants(b) {
  return (b << 1) - 1 | 0;
}

exports.baseIsValid = baseIsValid;
exports.totalCountOfCells = totalCountOfCells;
exports.totalRows = totalRows;
exports.totalColumns = totalColumns;
exports.totalSlants = totalSlants;
/* No side effect */
