// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function App(Props) {
  return React.createElement("div", undefined, React.createElement("p", undefined, "Perhaps"));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
