// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function getBase(part) {
  return part[0];
}

function getIndex(part) {
  return part[1];
}

function sameSquare(part1, part2) {
  return part1[0] === part2[0];
}

exports.getBase = getBase;
exports.getIndex = getIndex;
exports.sameSquare = sameSquare;
/* No side effect */
