// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function getBase(index_pair) {
  return index_pair[0];
}

function getIndex(index_pair) {
  return index_pair[1];
}

function sameSquare(part1, part2) {
  return getBase(part1) === getBase(part2);
}

exports.getBase = getBase;
exports.getIndex = getIndex;
exports.sameSquare = sameSquare;
/* No side effect */
