// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_math = require("rescript/lib/js/js_math.js");
var BasicPart = require("./BasicPart.bs.js");

function isValid(cell) {
  var base = BasicPart.getBase(cell);
  var index = BasicPart.getIndex(cell);
  return index <= Math.imul(base, base);
}

function rowIndex(cell) {
  var base = BasicPart.getBase(cell);
  var index = BasicPart.getIndex(cell);
  return Js_math.ceil_int(index / base);
}

function columnIndex(cell) {
  var base = BasicPart.getBase(cell);
  var index = BasicPart.getIndex(cell);
  return (index + base | 0) - Math.imul(base, rowIndex(cell)) | 0;
}

function rowColumnPair(cell) {
  return [
          rowIndex(cell),
          columnIndex(cell)
        ];
}

function baseRowColTriplet(cell) {
  return [
          BasicPart.getBase(cell),
          rowIndex(cell),
          columnIndex(cell)
        ];
}

function intersection(b, r, c) {
  return {
          base: b,
          index: (Math.imul(b, r) - b | 0) + c | 0
        };
}

var getBase = BasicPart.getBase;

var getIndex = BasicPart.getIndex;

var sameSquare = BasicPart.sameSquare;

exports.getBase = getBase;
exports.getIndex = getIndex;
exports.sameSquare = sameSquare;
exports.isValid = isValid;
exports.rowIndex = rowIndex;
exports.columnIndex = columnIndex;
exports.rowColumnPair = rowColumnPair;
exports.baseRowColTriplet = baseRowColTriplet;
exports.intersection = intersection;
/* No side effect */
