// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var BasicPart = require("./BasicPart.bs.js");

function isValid(cell) {
  var base = BasicPart.getBase(cell);
  var index = BasicPart.getIndex(cell);
  return index <= Math.imul(base, base);
}

exports.isValid = isValid;
/* No side effect */
