// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_List = require("rescript/lib/js/belt_List.js");

function intersection(b, r, c) {
  return {
          base: b,
          index: (Math.imul(b, r) - b | 0) + c | 0
        };
}

function rowCells(b, r) {
  var oneToBase = Belt_List.makeBy(b, (function (n) {
          return n + 1 | 0;
        }));
  return Belt_List.map(oneToBase, (function (param) {
                return intersection(b, r, param);
              }));
}

function columnCells(b, c) {
  var oneToBase = Belt_List.makeBy(b, (function (n) {
          return n + 1 | 0;
        }));
  return Belt_List.map(oneToBase, (function (__x) {
                return intersection(b, __x, c);
              }));
}

exports.intersection = intersection;
exports.rowCells = rowCells;
exports.columnCells = columnCells;
/* No side effect */
