// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function intersection(b, r, c) {
  return {
          base: b,
          index: (Math.imul(b, r) - b | 0) + c | 0
        };
}

exports.intersection = intersection;
/* No side effect */
