// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Cell = require("./Cell.bs.js");

function findByIntegers(b, r, c) {
  var cell_index = (Math.imul(b, r) - b | 0) + c | 0;
  var cell = {
    base: b,
    index: cell_index
  };
  if (Cell.isValid(cell)) {
    return cell;
  }
  
}

exports.findByIntegers = findByIntegers;
/* No side effect */
