// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_List = require("rescript/lib/js/belt_List.js");

function oneToN(n) {
  return Belt_List.makeBy(n, (function (i) {
                return i + 1 | 0;
              }));
}

exports.oneToN = oneToN;
/* No side effect */
