// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.bs.js");
var BasicParts = require("../src/BasicParts.bs.js");

Jest.describe("An cell with an invalid index ", (function (param) {
        return Jest.test("cell_with_invalid_index", (function (param) {
                      return Jest.Expect.toBe(false, Jest.Expect.expect(BasicParts.isValid({
                                          base: 5,
                                          index: 26
                                        })));
                    }));
      }));

Jest.describe("An cell with an valid index ", (function (param) {
        return Jest.test("cell_with_valid_index", (function (param) {
                      return Jest.Expect.toBe(true, Jest.Expect.expect(BasicParts.isValid({
                                          base: 5,
                                          index: 17
                                        })));
                    }));
      }));

/*  Not a pure module */
