// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Cell = require("../src/Square/Cell.bs.js");
var Jest = require("@glennsl/bs-jest/src/jest.bs.js");
var Util = require("../src/Square/Util.bs.js");
var Square = require("../src/Square/Square.bs.js");
var Symmetry = require("../src/Square/Symmetry.bs.js");
var Belt_List = require("rescript/lib/js/belt_List.js");

Jest.describe("Horizontal opposites of all cells of 5-square", (function (param) {
        return Jest.test("horizontal_opposites", (function (param) {
                      var allOppositeCells = Belt_List.map(Belt_List.keepMap(Belt_List.map(Util.oneToN(Square.totalCountOfCells(5)), (function (x) {
                                      return {
                                              base: 5,
                                              index: x
                                            };
                                    })), Symmetry.horizontalOpposite), Cell.getIndex);
                      return Jest.Expect.toEqual({
                                  hd: 5,
                                  tl: {
                                    hd: 4,
                                    tl: {
                                      hd: 3,
                                      tl: {
                                        hd: 2,
                                        tl: {
                                          hd: 1,
                                          tl: {
                                            hd: 10,
                                            tl: {
                                              hd: 9,
                                              tl: {
                                                hd: 8,
                                                tl: {
                                                  hd: 7,
                                                  tl: {
                                                    hd: 6,
                                                    tl: {
                                                      hd: 15,
                                                      tl: {
                                                        hd: 14,
                                                        tl: {
                                                          hd: 13,
                                                          tl: {
                                                            hd: 12,
                                                            tl: {
                                                              hd: 11,
                                                              tl: {
                                                                hd: 20,
                                                                tl: {
                                                                  hd: 19,
                                                                  tl: {
                                                                    hd: 18,
                                                                    tl: {
                                                                      hd: 17,
                                                                      tl: {
                                                                        hd: 16,
                                                                        tl: {
                                                                          hd: 25,
                                                                          tl: {
                                                                            hd: 24,
                                                                            tl: {
                                                                              hd: 23,
                                                                              tl: {
                                                                                hd: 22,
                                                                                tl: {
                                                                                  hd: 21,
                                                                                  tl: /* [] */0
                                                                                }
                                                                              }
                                                                            }
                                                                          }
                                                                        }
                                                                      }
                                                                    }
                                                                  }
                                                                }
                                                              }
                                                            }
                                                          }
                                                        }
                                                      }
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }, Jest.Expect.expect(allOppositeCells));
                    }));
      }));

Jest.describe("Vertical opposites of all cells of 5-square", (function (param) {
        return Jest.test("vertical_opposites", (function (param) {
                      var allOppositeCells = Belt_List.map(Belt_List.keepMap(Belt_List.map(Util.oneToN(Square.totalCountOfCells(5)), (function (x) {
                                      return {
                                              base: 5,
                                              index: x
                                            };
                                    })), Symmetry.verticalOpposite), Cell.getIndex);
                      return Jest.Expect.toEqual({
                                  hd: 21,
                                  tl: {
                                    hd: 22,
                                    tl: {
                                      hd: 23,
                                      tl: {
                                        hd: 24,
                                        tl: {
                                          hd: 25,
                                          tl: {
                                            hd: 16,
                                            tl: {
                                              hd: 17,
                                              tl: {
                                                hd: 18,
                                                tl: {
                                                  hd: 19,
                                                  tl: {
                                                    hd: 20,
                                                    tl: {
                                                      hd: 11,
                                                      tl: {
                                                        hd: 12,
                                                        tl: {
                                                          hd: 13,
                                                          tl: {
                                                            hd: 14,
                                                            tl: {
                                                              hd: 15,
                                                              tl: {
                                                                hd: 6,
                                                                tl: {
                                                                  hd: 7,
                                                                  tl: {
                                                                    hd: 8,
                                                                    tl: {
                                                                      hd: 9,
                                                                      tl: {
                                                                        hd: 10,
                                                                        tl: {
                                                                          hd: 1,
                                                                          tl: {
                                                                            hd: 2,
                                                                            tl: {
                                                                              hd: 3,
                                                                              tl: {
                                                                                hd: 4,
                                                                                tl: {
                                                                                  hd: 5,
                                                                                  tl: /* [] */0
                                                                                }
                                                                              }
                                                                            }
                                                                          }
                                                                        }
                                                                      }
                                                                    }
                                                                  }
                                                                }
                                                              }
                                                            }
                                                          }
                                                        }
                                                      }
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }, Jest.Expect.expect(allOppositeCells));
                    }));
      }));

Jest.describe("Descending opposites of all cells of 5-square", (function (param) {
        return Jest.test("descending_opposites", (function (param) {
                      var allOppositeCells = Belt_List.map(Belt_List.keepMap(Belt_List.map(Util.oneToN(Square.totalCountOfCells(5)), (function (x) {
                                      return {
                                              base: 5,
                                              index: x
                                            };
                                    })), Symmetry.descendingOpposite), Cell.getIndex);
                      return Jest.Expect.toEqual({
                                  hd: 25,
                                  tl: {
                                    hd: 20,
                                    tl: {
                                      hd: 15,
                                      tl: {
                                        hd: 10,
                                        tl: {
                                          hd: 5,
                                          tl: {
                                            hd: 24,
                                            tl: {
                                              hd: 19,
                                              tl: {
                                                hd: 14,
                                                tl: {
                                                  hd: 9,
                                                  tl: {
                                                    hd: 4,
                                                    tl: {
                                                      hd: 23,
                                                      tl: {
                                                        hd: 18,
                                                        tl: {
                                                          hd: 13,
                                                          tl: {
                                                            hd: 8,
                                                            tl: {
                                                              hd: 3,
                                                              tl: {
                                                                hd: 22,
                                                                tl: {
                                                                  hd: 17,
                                                                  tl: {
                                                                    hd: 12,
                                                                    tl: {
                                                                      hd: 7,
                                                                      tl: {
                                                                        hd: 2,
                                                                        tl: {
                                                                          hd: 21,
                                                                          tl: {
                                                                            hd: 16,
                                                                            tl: {
                                                                              hd: 11,
                                                                              tl: {
                                                                                hd: 6,
                                                                                tl: {
                                                                                  hd: 1,
                                                                                  tl: /* [] */0
                                                                                }
                                                                              }
                                                                            }
                                                                          }
                                                                        }
                                                                      }
                                                                    }
                                                                  }
                                                                }
                                                              }
                                                            }
                                                          }
                                                        }
                                                      }
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }, Jest.Expect.expect(allOppositeCells));
                    }));
      }));

Jest.describe("Ascending opposites of all cells of 5-square", (function (param) {
        return Jest.test("ascending_opposites", (function (param) {
                      var allOppositeCells = Belt_List.map(Belt_List.keepMap(Belt_List.map(Util.oneToN(Square.totalCountOfCells(5)), (function (x) {
                                      return {
                                              base: 5,
                                              index: x
                                            };
                                    })), Symmetry.ascendingOpposite), Cell.getIndex);
                      return Jest.Expect.toEqual({
                                  hd: 1,
                                  tl: {
                                    hd: 6,
                                    tl: {
                                      hd: 11,
                                      tl: {
                                        hd: 16,
                                        tl: {
                                          hd: 21,
                                          tl: {
                                            hd: 2,
                                            tl: {
                                              hd: 7,
                                              tl: {
                                                hd: 12,
                                                tl: {
                                                  hd: 17,
                                                  tl: {
                                                    hd: 22,
                                                    tl: {
                                                      hd: 3,
                                                      tl: {
                                                        hd: 8,
                                                        tl: {
                                                          hd: 13,
                                                          tl: {
                                                            hd: 18,
                                                            tl: {
                                                              hd: 23,
                                                              tl: {
                                                                hd: 4,
                                                                tl: {
                                                                  hd: 9,
                                                                  tl: {
                                                                    hd: 14,
                                                                    tl: {
                                                                      hd: 19,
                                                                      tl: {
                                                                        hd: 24,
                                                                        tl: {
                                                                          hd: 5,
                                                                          tl: {
                                                                            hd: 10,
                                                                            tl: {
                                                                              hd: 15,
                                                                              tl: {
                                                                                hd: 20,
                                                                                tl: {
                                                                                  hd: 25,
                                                                                  tl: /* [] */0
                                                                                }
                                                                              }
                                                                            }
                                                                          }
                                                                        }
                                                                      }
                                                                    }
                                                                  }
                                                                }
                                                              }
                                                            }
                                                          }
                                                        }
                                                      }
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }, Jest.Expect.expect(allOppositeCells));
                    }));
      }));

/*  Not a pure module */
